CREATE TABLE IF NOT EXISTS enrollments (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, user_email VARCHAR(255) NOT NULL, course_id BIGINT NOT NULL,
 course_title VARCHAR(160) NOT NULL, course_description VARCHAR(2000) NOT NULL, course_category VARCHAR(100) NOT NULL, course_level VARCHAR(40) NOT NULL,
 course_price DECIMAL(12,2) NOT NULL, course_status VARCHAR(20) NOT NULL, course_start_date DATE, course_end_date DATE, course_image_url VARCHAR(500),
 status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', progress_percent INTEGER NOT NULL DEFAULT 0,
 enrollment_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT uk_enrollments_user_course UNIQUE(user_id,course_id)
); CREATE INDEX IF NOT EXISTS idx_enrollments_user ON enrollments(user_id); CREATE INDEX IF NOT EXISTS idx_enrollments_course ON enrollments(course_id);
