spring.application.name=demo
# Configuración de base de datos de Supabase
spring.datasource.url=jdbc:postgresql://db.giazjwxohoakpzquqjrs.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Mu$$8H$2f_Cp6GF
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
