spring.application.name=user-service
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/register-courses
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=S3cur3K3yF0rJWT_FuneW3b_Curs0s_2026!xYz9
jwt.expiration=86400000

course-service.url=http://localhost:8082/api/courses